Why do we need to modify array ?

In real world application, datasets keep changing so to add new data points, removing unnecessary data, sometimes we need to merge or split datasets we need to modify arrays.

Unlike python lists, numpy arrays have fixed size, so we have to create new array everytime we modify it. Original array will remain as it is.

1. Insert function: It is used insert element at any index in array.

Syntax: np.insert(array, index, value, axis=none)

array --> original array

index --> position index

value --> new value to be inserted

axis --> none for flattened array

axis --> 0 for row-wise

1 for column wise 

In [2]:
import numpy as np 
#For 1D array
arr = np.array([10,20,30,40,50,60])

#insert 100 at 2
new_arr = np.insert(arr, 2, 100, axis=None)
print(new_arr)

#For 2D array
arr_2D = np.array([[1,2], [3,4]])

#insert a new row at 1
new_arr_2D = np.insert(arr_2D, 1, [5,6], axis=0)

print(new_arr_2D)

#insert a new column at 1 
new_arr_2D_2 = np.insert(arr_2D, 1, [5,6], axis=1)

print(new_arr_2D_2)

[ 10  20 100  30  40  50  60]
[[1 2]
 [5 6]
 [3 4]]
[[1 5 2]
 [3 6 4]]


2. Append: It is used to add any element at the end of an array.

In [3]:
arr_new = np.append(arr, [70,80])
print(arr_new)

[10 20 30 40 50 60 70 80]


3. Concatenate: It is used to concatenate/ join/ merge two or more arrays along an axis.

Syntax: np.concatenate((array1, array2), axis)

axis 0 --> vertical stacking 

axis 1 --> horizontal stacking

In [9]:
arr1 = np.array([1,2,3])
arr2= np.array([4,5,6])

new_arr = np.concatenate((arr1,arr2))
print(new_arr)


[1 2 3 4 5 6]


4. delete function: It is used to remove element at a specific index from an array and returns a new array. Original array remains unchanged  

Syntax: np.delete(array, index, axis=None)

In [16]:
new_arr= np.delete(arr1, 1, axis=None)
print(new_arr)

#For 2D array
arr_2D = np.array([[1,2,3], [4,5,6]])
new_arr2D = np.delete(arr_2D, 0, axis=0)#1 row
print(new_arr2D)

new_arr2 = np.delete(arr_2D, 0, axis=1)#1 column
print(new_arr2)

[1 3]
[[4 5 6]]
[[2 3]
 [5 6]]


5. Stacking: Combining two or more arrays horizontally or vertically is called stacking.

Syntax: vstack((arr1, arr2)) row wise 

hstack((arr1, arr2)) column wise

In [17]:
print(np.vstack((arr1, arr2)))
print(np.hstack((arr1, arr2)))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


6. Splitting: Dividing an array into multiple sub-arrays.

a. np.split() --> to split array into equal parts 

b. np.vsplit() --> to split array vertically.

c. np.hsplit() --> to split array horizontally.

In [20]:
print(np.split(arr, 2))#2--> number of parts in which array needs to be divided

[array([10, 20, 30]), array([40, 50, 60])]
