ARRAY PROPERTIES 

1. Shape attribute 

It helps us to check shape of an array (no. of rows and columns in an array). It is used when working with multi-dimensional data as it will help us to understand the structure of the array

In [1]:
import numpy as np 

arr_2d = np.array([[1,2,3], 
                   [4,5,6]])
print(arr_2d.shape)

(2, 3)


Here, 2=number of rows and 3=number of columns 

2. Size attribute 

With the help of this attribute, we can check the total number of elements in an array. It is used when working with a large dataset as it will help us to know how many values are stored.

In [2]:
arr = np.array([[10,20,30], [40,50,60]])

print(arr.size)

6


3. ndim attribute 

It helps us to check number of dimensions.

In [3]:
arr_1 = np.array([1,2,3])
arr_2 = np.array([[1,2,3], [4,5,6]])
arr_3 = np.array([[[1,2], [3,4], [5,6], [7,8]]])

print(arr_1.ndim)
print(arr_2.ndim)
print(arr_3.ndim)


1
2
3


Here, 1=1D array, 2=2D array, 3=3D array.

4. dtype attribute 

It helps us to check the datatype of elements stored in the array. 

In [4]:
arr = np.array([10,20,30.5,40])

print(arr.dtype)

float64


5. astype method

It is used to convert one datatype into another

Syntax: array.astype(new datatype)

In [5]:
arr = np.array([1.2, 2.5, 3.8])
print(arr.dtype)
int_arr = arr.astype(int)
print(int_arr)
print(int_arr.dtype)

float64
[1 2 3]
int64


NUMPY ARRAYS MATHEMATICAL OPERATIONS

In [6]:
arr = np.array([10,20,30])

print(arr + 5)
print(arr * 5)
print(arr ** 5)
print(arr / 5)
print(arr - 5)
print(arr % 5)
print(arr // 5)


[15 25 35]
[ 50 100 150]
[  100000  3200000 24300000]
[2. 4. 6.]
[ 5 15 25]
[0 0 0]
[2 4 6]


AGGREGATION FUNCTIONS

In [7]:
arr = np.array([10,20,30,40,50])

print(np.sum(arr))
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.var(arr))


150
50
10
30.0
14.142135623730951
200.0
