A. Broadcasting: It is a numpy way in which we perform operations on arrays of different shapes without using loops.

Operations are easier to perform and are performed at a faster speed.

In [4]:
#Without broadcasting 

prices = [100,200,300]
discount = 10 #10% discount
final_prices = []
for price in prices: 
    final_price = price - (price * discount/100)
    final_prices.append(final_price)
print(final_prices)


[90.0, 180.0, 270.0]


Without broadcasting we use loops which are very slow for large datasets.

In [5]:
#With broadcasting
import numpy as np

prices = np.array([100,200,300])
discount = 10 #scalar

final_prices = prices - (prices * discount/100)
print(final_prices)

[ 90. 180. 270.]


How numpy handles arrays of different shapes ?

1. Matching dimensions: If both arrays are of same dimension then element wise operations will be performed normally.

Eg.- [1,2,3] + [4,5,6] --> [5,7,9]

2. Expanding single elements: If one array has single element then numpy will expand it so that it can match with other array.

Eg. - [1,2,3] + [10] --> [11,12,13]

3. Incompatible shapes: If shapes are not matching then it will not expand.

Eg.- [1,2,3] + [1,2] --> error

In [7]:
matrix = np.array([[1,2,3], [4,5,6]])
vector = np.array([10,20,30])
result = matrix + vector
print(result)

[[11 22 33]
 [14 25 36]]


This is not possible with python lists.

B. Vectorization: Applying operation on an entire array (all elements) at once without using loops

It is 100x faster.

In [8]:
#Without vectorization 

list1 = [1,2,3]
list2 = [4,5,6]

result = [x+y for x,y in zip(list1, list2)]
print(result)

[5, 7, 9]


In [9]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

result = arr1 + arr2
print(result)

[5 7 9]


In [10]:
multiplied = arr1 * 3
print(multiplied)

[3 6 9]


Broadcasting --> 

It expans smaller arrays into larger arrays to match

Faster than loops

Vectorization --> 

Apply operation on entire array 

100x faster than loops

Used in matrix operations