Indexing and Slicing

With the help of indexing and slicing we can access any specific element on a specific position in array.

1. Indexing: Selecting a single element at a specific position from an array/ picking specific single element from an array,

ACCESS

Positive indexing: Left to right and starts from 0.

Negative indexing: Right to left and starts from -1.

Syntax: array_name[index] for 1d array

array_name[row, column] for 2d array

In [1]:
import numpy as np 

arr = np.array([10,20,30,40,50])

print(arr[0])#first element 
print(arr[2])#third element
print(arr[-1])#last element 

10
30
50


2. Slicing: Extracting subset of data/ Extracting subbarray from parent or main array/ Picking multiple elements from an array/ picking a portion of an array. (we choose sequential values).

Syntax: array_name[start:stop:step]

start=starting index
stop=1 step ahead from ending index (eg.- if we want to stop at 2 then stop=3)
step=default value 1

array_name[start:end] = start to end-1.
array_name[start:end:-1] = negative slicing, reverse (we can reverse the array without using loops).

In [2]:
arr = np.array([10,20,30,40,50,60])

print(arr[1:5])#index 1 to 4
print(arr[:4])#index 0 to 3
print(arr[::2])#every second element 
print(arr[::-1])#negative slicing

[20 30 40 50]
[10 20 30 40]
[10 30 50]
[60 50 40 30 20 10]


3. Fancy indexing: Selecting multiple elements at a time using a list of indices/ Selecting multiple elements at once.

In [5]:
arr = np.array([10,20,30,40,50,60])

print(arr[[0, 3, 4]])#10 40 50

[10 40 50]


4. Boolean masking: Filtering elements on the basis of a certain condition.

In [6]:
print(arr[arr>25])

[30 40 50 60]
