What is NumPy ?

Numpy stands for Numerical python created by Travis Oliphant in 2005. It is a library of python which helps in handling large amount of data quickly.

Features of Numpy : 
1) Speed (50-100 times faster )
2) Less memory
3) Easy math operations

In [ ]:
#Install numpy
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


Numpy arrays :

What is an array?

An array is a collection of values organized in a grid with one or more dimensions.

In NumPy:
- a 1-D array is like a list of numbers
- a 2-D array is like a matrix (rows and columns)
- a multi-dimensional array can have more than two axes

Arrays store elements of the same data type and allow fast numerical operations across the whole structure.

1D array

In [1]:
import numpy as np 

python_list = [1,2,3,4,5]
print("Python list:", python_list)

numpy_array = np.array([1,2,3,4,5])
print("Numpy array:", numpy_array)


Python list: [1, 2, 3, 4, 5]
Numpy array: [1 2 3 4 5]


2D array

In [2]:
arr_2d = np.array([[1,2,3], 
                   [4,5,6], 
                   [7,8,9]])
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Multi-dimensional array (Matrix)

In [3]:
import numpy as np

matrix = np.array([[1,2,3], 
                  [4,5,6]])

print(matrix)

[[1 2 3]
 [4 5 6]]


Creating arrays using python lists: 

Numpy has an array function which converts python list into array.

Syntax: np.array([ele1, ele2, ele3,])


In [4]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


Creating arrays with default values 

Numpy provides a built-in function to create array with default values 

1. Zeroes function: 

Syntax: np.zeros(shape) 

shape: size of array eg.- (3) for 1D and ((3,3)) for 2D

In [5]:
zeroes_array = np.zeros(3)
print(zeroes_array)

[0. 0. 0.]


2. Ones function 

Syntax: np.ones(shape)

In [6]:
ones_array = np.ones((2,3))
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]]


3. Full function: for a specific values

Syntax: np.full(shape, value)

In [7]:
filled = np.full((2,2), 7)
print(filled)

[[7 7]
 [7 7]]


Creating sequence of numbers in Numpy

Arange function :

Syntax: np.arange(start, stop, step)

In [8]:
arr = np.arange(1, 10, 2)

print(arr)

[1 3 5 7 9]


Creating identity matrices 

Identity matrix: It is a square matrix with ones on the diagonal and zeroes elsewhere

Eye function :

Syntax: np.eye(size)

In [9]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
