1. Reshaping: Changing the shape(dimensions) of an array without modifying data is called reshaping. 

array_name.reshape(rows, columns) specify new shape 
if dimensions match

It does not create a copy, it creates a view so it will affect  the original array.

In [1]:
import numpy as np 

arr = np.array([1,2,3,4,5,6])
reshaped_arr = arr.reshape(2,3)
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


2. Flattening: It helps to convert multidimensional array into 1d array.

.ravel() --> It returns a view.

.flatten() --> It returns a copy.

In [2]:
arr_2d = np.array([[1,2,3], [4,5,6]])

print(arr_2d.ravel())
print(arr_2d.flatten())


[1 2 3 4 5 6]
[1 2 3 4 5 6]
